### ISSUE TITLE
Actvividad 9

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-promastergamer#1]

**Comment by Heidi-19** [comment]
[Actividad 9 Funcionalidades incorporadas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-promastergamer/files/15183502/Actividad.9.Funcionalidades.incorporadas.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
